### ISSUE TITLE
Fix: 言語について

### ISSUE THREAD

**Issue by cutls** [nishlumi/gplusdon#19]
`navigator.language`で言語をjaとenで区別してそうですが、(static/js/util.js)自環境のChromeではen-usを返します。(モバイル[Android 8.0.0 SCV 35]/もPC[Chrome 71]共に)  
なお、Firefoxではjaでした。  
そのため、すべてのUIが英語で表示されてしまいます。  
ユーザーが言語を変更できる機能と、以下のコードなどで日本語を優先的に(おそらく日本語圏ユーザーが多数を占めると思うので)選択する機能をお願いしたいです。  
`var langlist=navigator.languages;`
`if(~langlist.indexOf("ja")){`
`	var lang="ja";`
`}else{`
`	var lang="en";`
`}`  
  
`navigator.languages`は利用できるすべての言語を配列で返します。日本語圏以外ユーザーのブラウザがどんな配列を返すかを検証したわけではありませんが、ご検討のほどよろしくお願いします。

**Comment by nishlumi** [comment]
ご報告ありがとうございます。

PCのChromeですと、言語の設定の順序を日本語・英語上げ下げすることで変わるのを確認できていたのですが、モバイルのChromeまでは確認していませんでした。
同じ設定でも変わらない可能性があるのですね。

アプリ側で任意にする言語設定、了解しました。
実装してみます。

**Comment by cutls** [comment]
ご指摘ありがとうございます。
確かに、言語設定は「日本語」より「英語(アメリカ合衆国)」のほうが上位で、これを入れ替えるとG+Donも日本語表示になりました。
当然過去に設定をいじった記憶もないので他にもデフォルトが英語になっちゃってる人がいるかもしれません。

**Comment by nishlumi** [comment]
本日の更新で実装いたしました。ご提案ありがとうございました。
