### ISSUE TITLE
feat: TL上のコントロールパネル

### ISSUE THREAD

**Issue by nacika-ins** [nishlumi/gplusdon#3]
![image](https://user-images.githubusercontent.com/1073376/52182950-6d6a1000-2846-11e9-9ed7-aa66fac8d59b.png)

このコントロールをどこか最適な場所に移動するか、小さくしたほうがよいかも。

**Comment by nishlumi** [comment]
2/14のアップデートにより機能の追加をしたことにともない幅高さを調整しました。
