### ISSUE TITLE
マルチポストはやめさせるべき

### ISSUE THREAD

**Issue by cutls** [nishlumi/gplusdon#32]
マルチポスト(同内容のトゥートを複数アカウントに投稿)は連合の概念の真逆を行くので廃止してほしい。

**Comment by nishlumi** [comment]
本アプリだけかと思いましたが、他のマストドンクライアントでも存在する機能のようで、「クロスポスト」機能という正式な名称がある機能のようです。（世間的にもマルチポストとの違いが分かりづらいようですが）

ぜひ他のアプリの開発者の方にも同じ要望を伝えて、すべてのクライアントからクロスポスト機能を根絶できるよう頑張ってください。
他のアプリでも削除を確認出来次第、それに追随させていただきます。

**Comment by cutls** [comment]
@nishlumi あれだけ独自性売ってきて都合の悪いことになれば他の追従か。多分この返信も都合が悪いからこれに返信することはないだろうね。あとから追従する気があればCloseしないだろうし。

まず、Mastodon本体にない機能に正式名称があるわけがない。基本的にこの２つは同義だ。
自分の考えの上に限っては、TwitterとFediverseに同時投稿することをクロスポスト、Fediverse同士ならマルチポストと呼ぶことにしている、というだけの話。
確かにマルチポストに対応し(なおかつ売りにまでしている)クライアントは無いわけでは無いが、ほとんど存在しないので、「みんなやってるから私も」なんてのは通用しないよ。[分散SNSフォーラム](http://distsn.org/mastodon-apps.html)によると対応してるクライアントは全体の5%にも満たない程度だ。

例えばG+Donを使って複数アカウントに同時投稿するとかいう愚行をしたら、そのどちらのアカウントもフォローしてくれているユーザーは、どちらをお気に入り登録やブーストするのか。連合を眺めてて同じトゥートが何個も並んだらどう思うか。それで印象が悪くならないのか。ホームで片方しか見てなかったのに、もう一方が流れてきたら、どちらかがどちらかをパクったのかと思うだろう。

私の居るインスタンスでは、G+Donからのログインを弾く予定だ。私は管理人ではないので決める決定権はないし、管理人がそう決めたんだろう。理由は以上の通りだと思う。**私の個人的な主義主張をあなたにも、管理人にも押し付けているわけではない。**

ここからは別な話。私がIssue書いてももうどうせ読まないだろうからここに書く。
Markdownにしろ位置情報にしろ、クライアントはG+Donしかないとでも思っているのか。Webとか他のサードパーティクライアントから見たら無意味な文字列だ。そういうのを汎用的なインスタンスに求めないでほしい。このトゥートの内容すべて見るにはG+Don使ってね、っていう宣伝をしたいのか？あまりにもアンフェアだ。G+DonはMastodonクライアントであって、Google+のクライアントでも、その他スタンドアロンなSNSのクライアントでもない。
あと、XSS脆弱性があることも報告しておく。第三者が任意のJavaScript実行できるよ。どこにあるかはさすがに簡単な箇所だからわかってると思うけど。

あなたが喧嘩腰に煽り口調使うからつい硬く書きすぎました。謝罪します。せめて未収載以下の対応にするなど、あなたの大人な、Fediverseのためになる対応を心より祈っています。

**Comment by nishlumi** [comment]
問題点を把握し、isshueを復活させました。この件につきましては対応させていただきます。
別の問題については、こっそりと教えていただいて助かりました。
大恥をかくところでした・・・ありがとうございます。

**Comment by nishlumi** [comment]
本日の更新で反映いたしました。よろしくお願い致します。
