### ISSUE TITLE
not working with pleroma instance

### ISSUE THREAD

**Issue by roytam1** [nishlumi/gplusdon#36]
after login in pleroma OAuth page, there is no new server appearing in server list.

**Comment by nishlumi** [comment]
Thank you, your report.
Is pleroma the Mastodon server name? Could you please tell me all the URLs of Pleroma?

**Comment by roytam1** [comment]
> Is pleroma the Mastodon server name?

this is another ActivityPub server software that provides mastodon-compatible API access. https://ja.mstdn.wiki/Pleroma

pleroma instance may provide different format of `code` and/or `client_id`, you may check https://github.com/NanaMorse/Cuckoo.Plus/commit/ac698c505b2954a822b0613fed9e432d3d8fc276 and https://github.com/NanaMorse/Cuckoo.Plus/commit/e7e72642387e6769f95edba1529a03298de642e1 for your reference.

**Comment by nishlumi** [comment]
Is Pleroma not mastodon, but compatible with mastodon?

 Thank you for useful information!
(Unfortunately, G+Don does not yet support other ActivityPub software...)
I would like to support other ActivityPub software compatible software in the future.

**Comment by roytam1** [comment]
> Is Pleroma not mastodon, but compatible with mastodon?

in API level, yes.

**Comment by nishlumi** [comment]
I fixed a bug to show Pleroma instance by version 1.0.15.
But I confirmed one instance. Please confirm your favourited instance.
