### ISSUE TITLE
返信が全部表示されない

### ISSUE THREAD

**Issue by array** [nishlumi/gplusdon#37]
返信を書いたときにもとのトゥートの下に出るはずですが全部でません。スクロールバーもでません、
![Screenshot_2019-03-20 G+Don](https://user-images.githubusercontent.com/179274/54685452-2fa51a80-4b5a-11e9-9308-1b2d884f3838.png)

**Comment by array** [comment]
Firefoxでフォントがうまく設定されないようです。明らかにChromeとFirefoxとフォントが違いますね。
Chromeだときちんと全部でました。

**Comment by nishlumi** [comment]
返信一覧の最小表示ではあえて部分的にしか表示しない仕様になっております。
返信ボタンを押すことでスクロールバーが表示され（場合によっては最新の返信コメントを再取得）、
見ることができるようになっております。

ただ同様の問い合わせを受けており、分かりづらい表示なのは認識していますので、
もう少し良い形で表示するよう、改修を検討しております。

ご確認ありがとうございました。

**Comment by nishlumi** [comment]
1.0.14にて表示の仕方を変更しました。紛らわしくなく、コメント閲覧の早見ができる表示を目指していますが、まだ調整の余地あると思っていますので、今後も案や問題点をご指摘いただけると助かります。
