### ISSUE TITLE
タイムラインでユーザーのポップアップが出たままになる

### ISSUE THREAD

**Issue by gaeeyo** [nishlumi/gplusdon#42]
マウスポインタを図のように移動すると、高い確率でユーザーのポップアップが表示されたままになってしまう。
ポップアップ内にポインタを移動してから、再び外に出すとポップアップは消えます。
![image](https://user-images.githubusercontent.com/344396/56544267-edcf2000-65ae-11e9-8389-3e23619bfdf6.png)

Chrome 73.0.3683.103

**Comment by nishlumi** [comment]
ご報告ありがとうございます。
修正の目処が立ちましたので次のバージョンで反映予定です。
