### ISSUE TITLE
design: zoom 80%程で左側ペインの余白にずれが生じる

### ISSUE THREAD

**Issue by nacika-ins** [nishlumi/gplusdon#6]
## 現状
![image](https://user-images.githubusercontent.com/1073376/52183028-2a5c6c80-2847-11e9-8929-d8a4498dcf5e.png)

## 提案内容

Zoomサイズに応じてCardの余白自体も調整する

**Comment by nishlumi** [comment]
2/15のアップデートで調整しました。
