### ISSUE TITLE
design: 投稿領域が灰色のため無効領域に見える

### ISSUE THREAD

**Issue by nacika-ins** [nishlumi/gplusdon#7]
## 現状
![image](https://user-images.githubusercontent.com/1073376/52183111-f9c90280-2847-11e9-8961-b09c2d1f9607.png)

## 提案内容
灰色部分を白色にし、フォーカスを当てる。
色がなくても、フォーカスがあたっていることによって入力領域だと気づける。

**Comment by nishlumi** [comment]
ご提案ありがとうございます。灰色は色を薄くし、入力領域の下部分のボーダーを色付きにしてみました。
次のアップデートで反映予定ですが、使いやすさと印象にもつながるため、今後も要改善事項と判断します。
