### ISSUE TITLE
design: カードの余白が大きい

### ISSUE THREAD

**Issue by nacika-ins** [nishlumi/gplusdon#8]
## 現状

![image](https://user-images.githubusercontent.com/1073376/52183159-6217e400-2848-11e9-832d-34da74f1da06.png)

## 提案内容

カードの縦の余白が広いので横の余白と合わせたほうが見栄えがよくなりそう

**Comment by nishlumi** [comment]
1.0.11にて若干調整しました。
一旦閉めさせていただきますが、今後も要課題かもしれません。
